---
title: '112916'
author: "Yunjae"
date: "November 29, 2016"
output: html_document
---

```{r include = FALSE}
library(dplyr)
library(readr)
```

```{r}
raw_name <-  "~/sanfran-crime-old/train.csv"
Crime <- readr::read_csv(raw_name, n_max = 5000000)
save(Crime, file = "Crime.rda")
```

```{r}
load("~/sanfran-crime-old/Crime.rda")
Crime <-
  Crime %>% 
  group_by(Category) %>%
  filter(n() > 20000) %>%
  mutate(hour = lubridate::hour(Dates), month = lubridate::month(Dates)) %>%
  filter(Category %in% c("LARCENY/THEFT", "DRUG/NARCOTIC", "ROBBERY", "BURGLARY", "ASSAULT")) %>%
  mutate(DayOfWeek = ifelse(DayOfWeek %in% c("Saturday","Sunday"), 1, 0))%>%
  sample_n(size = 10000)

names(Crime)
```

```{r}
samplesize <- floor(0.75 * nrow(Crime))
set.seed(123)
all_indices = c(1:nrow(Crime))
train_indices = sample(seq_len(nrow(Crime)), size = samplesize)
test_indices = setdiff(all_indices, train_indices)
all( ! test_indices %in% train_indices)


# These are DATA FRAMES (DATA)
# Train_data
Train_crime = Crime[train_indices, ]
save(Train_crime, file="Train_crime.rda")
# Test_data
Test_crime = Crime[test_indices, ] 
save(Test_crime, file="Test_crime.rda")
```

