---
title: "SVM"
author: "Phuc Nguyen"
date: "12/8/2016"
output: html_document
---

```{r}
load("Train_data.rda")
load("Test_data.rda")
library(e1071)
library(ggplot2)
library(dplyr)
```

## Singular Value Classifier:

Classify crime based on location (X: latitude, Y: longtitude), time (hour) and day of week (day_num)

```{r}
mod <- svm(as.factor(Category) ~ day_num + X + Y + hour, data=Train_data, kernel = "radial", cost = 10, gamma = 1)
pred <- predict(mod, newdata=Test_data)
foo <- table(Test_data$Category, pred)
foo
1- (sum(diag(foo))/sum(foo))
```

Error rate of about 68%. The linear kernel yields higher error rate.

```{r}
mod <- svm(as.factor(Category) ~ day_num + X + Y + hour, data=Train_data, kernel = "linear", cost = 10)
pred <- predict(mod, newdata=Test_data)
foo <- table(Test_data$Category, pred)
foo
1- (sum(diag(foo))/sum(foo))
```

## Tune the svm

```{r}
tune.mod <- tune(svm, as.factor(Category)~day_num+X+Y+hour, data=Train_data, kernel="radial", ranges=list(cost=c(1,10,100), gamma=c(0.5,1,2)), tunecontrol = tune.control(sampling = "fix", cross=5))
```

Best cost is 100, gamma is 2

```{r}
mod <- svm(as.factor(Category) ~ day_num + X + Y + hour, data=Train_data, kernel = "radial", cost = 100, gamma = 2)
pred <- predict(mod, newdata=Test_data)
foo <- table(Test_data$Category, pred)
foo
1- (sum(diag(foo))/sum(foo))
ggplot(Test_data,aes(X,Y, colour=pred)) + geom_point() + xlim(-122.35, -122.55) + ylim(37.7,37.85)
```
```{r}
in_pred <- predict(mod, newdata=Train_data)
Gotwrong <- subset(Train_data, Category != in_pred)
Train_data$in_pred <- in_pred
ggplot(Train_data,aes(X,Y, colour=in_pred))  + geom_point(aes(alpha=1/3)) + xlim(-122.35, -122.55) + ylim(37.7,37.85) #+geom_point(data=Gotwrong, aes(X,Y, color=NA, alpha=1/20))
```